// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEUhVl29rciXpBuVh11ShimiJ9BqD9J8E',
    appId: '1:390560947891:web:aa3e192391e1b5aea65ac6',
    messagingSenderId: '390560947891',
    projectId: 'yourchat-558fe',
    authDomain: 'yourchat-558fe.firebaseapp.com',
    storageBucket: 'yourchat-558fe.firebasestorage.app',
    measurementId: 'G-7Y8B05M2XL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgrFtBVkGZvWRG9e8Yo8K8QUJmVkvtvTw',
    appId: '1:390560947891:android:585fdc14ecda49cca65ac6',
    messagingSenderId: '390560947891',
    projectId: 'yourchat-558fe',
    storageBucket: 'yourchat-558fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlwoQZJon4p8pjM38fJBIoAZyPLQWvBdY',
    appId: '1:390560947891:ios:e51a0e8740ee83b4a65ac6',
    messagingSenderId: '390560947891',
    projectId: 'yourchat-558fe',
    storageBucket: 'yourchat-558fe.firebasestorage.app',
    iosBundleId: 'com.example.yourchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlwoQZJon4p8pjM38fJBIoAZyPLQWvBdY',
    appId: '1:390560947891:ios:e51a0e8740ee83b4a65ac6',
    messagingSenderId: '390560947891',
    projectId: 'yourchat-558fe',
    storageBucket: 'yourchat-558fe.firebasestorage.app',
    iosBundleId: 'com.example.yourchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEUhVl29rciXpBuVh11ShimiJ9BqD9J8E',
    appId: '1:390560947891:web:cf345bc0862ea927a65ac6',
    messagingSenderId: '390560947891',
    projectId: 'yourchat-558fe',
    authDomain: 'yourchat-558fe.firebaseapp.com',
    storageBucket: 'yourchat-558fe.firebasestorage.app',
    measurementId: 'G-1B46MCN3RK',
  );
}
